obj-$(CONFIG_SND_SOC_AW88230) += snd-soc-aw88230.o
snd-soc-aw88230-y := aw882xx.o \
	aw882xx_bin_parse.o \
	aw882xx_calib.o \
	aw882xx_device.o \
	aw882xx_dsp.o \
	aw882xx_init.o \
	aw882xx_monitor.o \
	aw882xx_spin.o
